# Generated by Django 2.1.3 on 2018-11-29 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024)),
                ('tipo', models.CharField(choices=[('REG', 'Regular'), ('INCOMP', 'In-company')], default='REG', max_length=16)),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(choices=[('REG', 'Regular'), ('TRANS', 'Transferência'), ('CANC', 'Cancelamento'), ('REP', 'Reposição')], default='REG', max_length=16)),
                ('aluno', models.ForeignKey(on_delete='PROTECT', related_name='inscricoes', to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('datahora_fechamento_inscricao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete='PROTECT', related_name='turmas', to='core.Curso')),
                ('professor', models.ForeignKey(on_delete='PROTECT', related_name='turmas', to='core.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turma',
            field=models.ForeignKey(on_delete='PROTECT', related_name='inscricoes', to='core.Turma'),
        ),
    ]
